### ISSUE TITLE
Version danoise ?

### ISSUE THREAD

**Issue by Alkarex** [Deevad/peppercarrot_ep04_translation#27]
Bonjour,
Je vois que le danois s'est arrêté avec cet épisode 4. Seriez-vous intéressé par une version danoise ?

**Comment by Alkarex** [comment]
Question bonus : Il y a quelques erreurs en danois dans les épisodes précédents. Êtes-vous preneurs de patchs ?

**Comment by Deevad** [comment]
Hi @Alkarex,
Merci! and Thank you for the proposition. (I'm writing here in English for the other translators who subscribe to the bug reports of this repository).

Sure, the Dansk version so far was provided by the friendly Juan Jose Segura in his effort of learning the langage. He made this as an exercice, and it was proofread by his teacher, but I'm not expecting here something 100% perfect. It was made long time ago (probably more than 1 year old). So, I'm very open for correction, pull-request, and the next part. 

If you want, we can test on episode 4 with pull-request ; and if it works fine, I'll give you permission to edit all the 'master' of the other episode later. Thanks for the help !

**Comment by Alkarex** [comment]
Done in https://github.com/Deevad/peppercarrot_ep04_translation/pull/28
We will read it again tomorrow, but feedback already welcome :-)
